#!/bin/bash
DIRNAME=$(cd `dirname $0` && pwd)
hadoop jar $DIRNAME/../lib/phoenix.jar phoenix.CountLinkText -D mapred.speculative.execution=false -D mapreduce.fileoutputcommitter.marksuccessfuljob=false "$@"

