#!/bin/bash
DIRNAME=$(cd `dirname $0` && pwd)
LIBDIR=$DIRNAME/../lib
LUCENE=$LIBDIR/lucene-core-3.0.3.jar 
HADOOP_CLASSPATH=$LUCENE hadoop jar $LIBDIR/phoenix.jar phoenix.LinkProbabilityFinder -libjars $LUCENE -D mapred.speculative.execution=false -D mapred.child.java.opts=-Xmx1024M "$@"

