#!/bin/bash
#raw bzip2 file is $1
#working dir is $2
#hdfs dir is $3
DIRNAME=$(cd `dirname $0` && pwd)
LIBDIR=$DIRNAME/../ruby
JAR=$LIBDIR/phoenix.jar
PYTHONIOENCODING=utf_8 python -m gensim.corpora.wikicorpus $1 $2 | hadoop jar $JAR phoenix.StreamToHdfs $3/gensim_titles.txt
PYTHONIOENCODING=utf_8 python $DIRNAME/lda.py $2 | hadoop jar $JAR phoenix.GensimLDAMapFileSaver $3/gensim_titles.txt $3/unsorted_lda.seq
#cat /mnt/fatman/en_20100904_gensim_topics.txt | hadoop jar $JAR phoenix.GensimLDAMapFileSaver $3/gensim_titles.txt $3/unsorted_lda.seq
hadoop jar $JAR phoenix.SequenceFileSorter -D mapred.input.dir=$3/unsorted_lda.seq -D mapred.output.dir=$3/sorted_lda
