#!/bin/bash
DIRNAME=$(cd `dirname $0` && pwd)
LANG_DIR=$1
/opt/hadoop/bin/hadoop jar $DIRNAME/../lib/phoenix.jar phoenix.SequenceFileSorter -D mapred.input.dir=$LANG_DIR/unsorted_text.seq -D mapred.output.dir=$LANG_DIR/sorted_text
